 ###
##
##  Copyright cmdlp
##
##  LICENSE: You are allowed to include this code in your product, but you need to refer to this repository.
##
##  Makefile
##
 ###

ifeq ($(OS),Windows_NT)
RM := del
else
RM := rm
endif

clean:
	$(RM) $(wildcard *-rgba.png)
